name: azure-ai-agent-service-demo
channels:
  - conda-forge
  - defaults
  - jupyter
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pip:
    - -r requirements.txt
    - -r requirements-codequality.txt
